In [2]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

data=pd.read_csv(r"C:\Users\Jayaraj.V\OneDrive\Desktop\SIH\flight_data.csv")
numeric_cols = data.select_dtypes(include=['number']).columns
categorical_cols = data.select_dtypes(include=['object']).columns
numeric_imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
data[numeric_cols] = numeric_imputer.fit_transform(data[numeric_cols])
categorical_imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
data[categorical_cols] = categorical_imputer.fit_transform(data[categorical_cols])
data.to_csv(r'C:\Users\Jayaraj.V\OneDrive\Desktop\SIH\new\new cleaned flight.csv', index=False)

In [3]:
data=pd.read_csv(r"C:\Users\Jayaraj.V\OneDrive\Desktop\SIH\new\new cleaned flight.csv")

In [4]:
data.isnull()

,icao24,callsign,origin_country,time_position,last_contact,longitude,latitude,baro_altitude,on_ground,velocity,heading,vertical_rate,geo_altitude,squawk,spi,position_source
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10851,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10852,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10853,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10854,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10855,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
data.dropna()

,icao24,callsign,origin_country,time_position,last_contact,longitude,latitude,baro_altitude,on_ground,velocity,heading,vertical_rate,geo_altitude,squawk,spi,position_source
0,4b1816,SWR438A,Switzerland,1.723570e+09,1.723570e+09,4.3309,50.2606,11887.200000,False,226.33,120.00,0.000000,12405.36000,2055.000000,False,0.0
1,a4754b,N387A,United States,1.723570e+09,1.723570e+09,-110.1006,36.2796,12184.380000,False,203.77,271.30,0.000000,12847.32000,3574.610393,False,0.0
2,80162d,AXB747,India,1.723570e+09,1.723570e+09,56.2388,24.8851,5486.400000,False,179.34,306.84,-0.330000,5844.54000,3574.610393,False,0.0
3,e8027d,LPE2086,Chile,1.723570e+09,1.723570e+09,-77.2945,-11.4694,3352.800000,False,145.74,165.28,-4.880000,3589.02000,3574.610393,False,0.0
4,a57b26,N452SM,United States,1.723570e+09,1.723570e+09,-104.9779,40.3572,2537.460000,False,55.40,190.16,-1.300000,2659.38000,3574.610393,False,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10851,a05dba,UAL1782,United States,1.723570e+09,1.723570e+09,-92.6421,41.5110,10058.400000,False,252.07,84.85,0.330000,10607.04000,3574.610393,False,0.0
10852,458666,CAT762,Denmark,1.723570e+09,1.723570e+09,4.5822,54.2710,11887.200000,False,247.63,57.73,0.000000,12306.30000,1145.000000,False,0.0
10853,c067ae,ACA410,Canada,1.723570e+09,1.723570e+09,-73.7477,45.4598,6225.540757,True,1.54,227.81,-0.175294,6547.50637,6334.000000,False,0.0
10854,c00734,WJA1596,Canada,1.723570e+09,1.723570e+09,-114.4152,47.7274,10668.000000,False,239.54,109.84,0.330000,11003.28000,3574.610393,False,0.0
10855,a60bbd,WUP489,United States,1.723570e+09,1.723570e+09,-78.4164,41.8229,10668.000000,False,229.40,98.51,0.330000,10988.04000,6513.000000,False,0.0

In [6]:
boolean_cols = data.select_dtypes(include=['bool']).columns
data[boolean_cols] = data[boolean_cols].astype(int)

In [7]:
data

,icao24,callsign,origin_country,time_position,last_contact,longitude,latitude,baro_altitude,on_ground,velocity,heading,vertical_rate,geo_altitude,squawk,spi,position_source
0,4b1816,SWR438A,Switzerland,1.723570e+09,1.723570e+09,4.3309,50.2606,11887.200000,0,226.33,120.00,0.000000,12405.36000,2055.000000,0,0.0
1,a4754b,N387A,United States,1.723570e+09,1.723570e+09,-110.1006,36.2796,12184.380000,0,203.77,271.30,0.000000,12847.32000,3574.610393,0,0.0
2,80162d,AXB747,India,1.723570e+09,1.723570e+09,56.2388,24.8851,5486.400000,0,179.34,306.84,-0.330000,5844.54000,3574.610393,0,0.0
3,e8027d,LPE2086,Chile,1.723570e+09,1.723570e+09,-77.2945,-11.4694,3352.800000,0,145.74,165.28,-4.880000,3589.02000,3574.610393,0,0.0
4,a57b26,N452SM,United States,1.723570e+09,1.723570e+09,-104.9779,40.3572,2537.460000,0,55.40,190.16,-1.300000,2659.38000,3574.610393,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10851,a05dba,UAL1782,United States,1.723570e+09,1.723570e+09,-92.6421,41.5110,10058.400000,0,252.07,84.85,0.330000,10607.04000,3574.610393,0,0.0
10852,458666,CAT762,Denmark,1.723570e+09,1.723570e+09,4.5822,54.2710,11887.200000,0,247.63,57.73,0.000000,12306.30000,1145.000000,0,0.0
10853,c067ae,ACA410,Canada,1.723570e+09,1.723570e+09,-73.7477,45.4598,6225.540757,1,1.54,227.81,-0.175294,6547.50637,6334.000000,0,0.0
10854,c00734,WJA1596,Canada,1.723570e+09,1.723570e+09,-114.4152,47.7274,10668.000000,0,239.54,109.84,0.330000,11003.28000,3574.610393,0,0.0
10855,a60bbd,WUP489,United States,1.723570e+09,1.723570e+09,-78.4164,41.8229,10668.000000,0,229.40,98.51,0.330000,10988.04000,6513.000000,0,0.0

In [8]:
data.rename(columns={
    'icao24': 'Aircraft_ICAO24',
    'callsign': 'Callsign',
    'origin_country': 'Origin_Country',
    'time_position': 'Time_Position',
    'last_contact': 'Last_Contact',
    'longitude': 'Longitude',
    'latitude': 'Latitude',
    'baro_altitude': 'Barometric_Altitude',
    'on_ground': 'On_Ground',
    'velocity': 'Velocity',
    'heading': 'Heading',
    'vertical_rate': 'Vertical_Rate',
    'geo_altitude': 'Geometric_Altitude',
    'squawk': 'Squawk_Code',
    'spi': 'SPI_Indicator',
    'position_source': 'Position_Source'
}, inplace=True)

In [9]:
df = data.round(2)

In [10]:
df

,Aircraft_ICAO24,Callsign,Origin_Country,Time_Position,Last_Contact,Longitude,Latitude,Barometric_Altitude,On_Ground,Velocity,Heading,Vertical_Rate,Geometric_Altitude,Squawk_Code,SPI_Indicator,Position_Source
0,4b1816,SWR438A,Switzerland,1.723570e+09,1.723570e+09,4.33,50.26,11887.20,0,226.33,120.00,0.00,12405.36,2055.00,0,0.0
1,a4754b,N387A,United States,1.723570e+09,1.723570e+09,-110.10,36.28,12184.38,0,203.77,271.30,0.00,12847.32,3574.61,0,0.0
2,80162d,AXB747,India,1.723570e+09,1.723570e+09,56.24,24.89,5486.40,0,179.34,306.84,-0.33,5844.54,3574.61,0,0.0
3,e8027d,LPE2086,Chile,1.723570e+09,1.723570e+09,-77.29,-11.47,3352.80,0,145.74,165.28,-4.88,3589.02,3574.61,0,0.0
4,a57b26,N452SM,United States,1.723570e+09,1.723570e+09,-104.98,40.36,2537.46,0,55.40,190.16,-1.30,2659.38,3574.61,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10851,a05dba,UAL1782,United States,1.723570e+09,1.723570e+09,-92.64,41.51,10058.40,0,252.07,84.85,0.33,10607.04,3574.61,0,0.0
10852,458666,CAT762,Denmark,1.723570e+09,1.723570e+09,4.58,54.27,11887.20,0,247.63,57.73,0.00,12306.30,1145.00,0,0.0
10853,c067ae,ACA410,Canada,1.723570e+09,1.723570e+09,-73.75,45.46,6225.54,1,1.54,227.81,-0.18,6547.51,6334.00,0,0.0
10854,c00734,WJA1596,Canada,1.723570e+09,1.723570e+09,-114.42,47.73,10668.00,0,239.54,109.84,0.33,11003.28,3574.61,0,0.0
10855,a60bbd,WUP489,United States,1.723570e+09,1.723570e+09,-78.42,41.82,10668.00,0,229.40,98.51,0.33,10988.04,6513.00,0,0.0

In [11]:
df.drop_duplicates()

,Aircraft_ICAO24,Callsign,Origin_Country,Time_Position,Last_Contact,Longitude,Latitude,Barometric_Altitude,On_Ground,Velocity,Heading,Vertical_Rate,Geometric_Altitude,Squawk_Code,SPI_Indicator,Position_Source
0,4b1816,SWR438A,Switzerland,1.723570e+09,1.723570e+09,4.33,50.26,11887.20,0,226.33,120.00,0.00,12405.36,2055.00,0,0.0
1,a4754b,N387A,United States,1.723570e+09,1.723570e+09,-110.10,36.28,12184.38,0,203.77,271.30,0.00,12847.32,3574.61,0,0.0
2,80162d,AXB747,India,1.723570e+09,1.723570e+09,56.24,24.89,5486.40,0,179.34,306.84,-0.33,5844.54,3574.61,0,0.0
3,e8027d,LPE2086,Chile,1.723570e+09,1.723570e+09,-77.29,-11.47,3352.80,0,145.74,165.28,-4.88,3589.02,3574.61,0,0.0
4,a57b26,N452SM,United States,1.723570e+09,1.723570e+09,-104.98,40.36,2537.46,0,55.40,190.16,-1.30,2659.38,3574.61,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10851,a05dba,UAL1782,United States,1.723570e+09,1.723570e+09,-92.64,41.51,10058.40,0,252.07,84.85,0.33,10607.04,3574.61,0,0.0
10852,458666,CAT762,Denmark,1.723570e+09,1.723570e+09,4.58,54.27,11887.20,0,247.63,57.73,0.00,12306.30,1145.00,0,0.0
10853,c067ae,ACA410,Canada,1.723570e+09,1.723570e+09,-73.75,45.46,6225.54,1,1.54,227.81,-0.18,6547.51,6334.00,0,0.0
10854,c00734,WJA1596,Canada,1.723570e+09,1.723570e+09,-114.42,47.73,10668.00,0,239.54,109.84,0.33,11003.28,3574.61,0,0.0
10855,a60bbd,WUP489,United States,1.723570e+09,1.723570e+09,-78.42,41.82,10668.00,0,229.40,98.51,0.33,10988.04,6513.00,0,0.0

In [12]:
df.to_csv(r'C:\Users\Jayaraj.V\OneDrive\Desktop\SIH\new\CLEANED DATA.csv', index=False)